id: P009551
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ57645
  title: གསང་འདུས་རྒྱ་ཆེར་བཤད་པ་སྒྲོན་མ་གསལ་བའི་ཚིག་དོན་ཇི་བཞིན་འབྱེད་པའི་མཆན་གྱི་ཡང་འགྲེལ།
  author: ''
  volumes:
    edecd7366bb949a5b14c3bf1497c8a99:
      image_group_id: I4CZ57647
      title: ''
      volume_number: 1
      total_pages: 1014
