id: IA52A42EA
legacy_id: P009551
ocr_import_info:
  bdrc_scan_id: W4CZ57645
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T00:25:44'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T20:36:20.110943+00:00'
last_modified: 2022-09-04 04:37:22.544841
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W4CZ57645
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW4CZ57645
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསང་འདུས་རྒྱ་ཆེར་བཤད་པ་སྒྲོན་མ་གསལ་བའི་ཚིག་དོན་ཇི་བཞིན་འབྱེད་པའི་མཆན་གྱི་ཡང་འགྲེལ།
  author: ཙོང་ཁ་པ་བློ་བཟང་གྲགས་པ།
statistics:
  ocr_word_mean_confidence_index: 0.9481299499590518
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I4CZ57647:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ57647
      total_pages: 1014
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4CZ57647.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9481299499590518
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
